// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARdcLYdp2uX5rOjkiZ3q9_J1aB1eXKFds',
    appId: '1:307712945269:web:d5049f8ef9cf6d3b329c3c',
    messagingSenderId: '307712945269',
    projectId: 'chatty-4bd60',
    authDomain: 'chatty-4bd60.firebaseapp.com',
    storageBucket: 'chatty-4bd60.appspot.com',
    measurementId: 'G-G5ZQ8W3Y1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB3loBUAPnHdFurRFmEvPi7q-jf_sbLVg',
    appId: '1:307712945269:android:81abf1a77470c4b3329c3c',
    messagingSenderId: '307712945269',
    projectId: 'chatty-4bd60',
    storageBucket: 'chatty-4bd60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBx_7WlIohlQ8tK3r5UfWT6jp5v4gdrT8',
    appId: '1:307712945269:ios:850e8c8312782335329c3c',
    messagingSenderId: '307712945269',
    projectId: 'chatty-4bd60',
    storageBucket: 'chatty-4bd60.appspot.com',
    iosClientId: '307712945269-7i1e086lbial8uklinakfna4mi6i1ts8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
